/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraciasInfinitasRouteImport } from './routes/gracias-infinitas'
import { Route as IndexRouteImport } from './routes/index'

const GraciasInfinitasRoute = GraciasInfinitasRouteImport.update({
  id: '/gracias-infinitas',
  path: '/gracias-infinitas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gracias-infinitas': typeof GraciasInfinitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gracias-infinitas': typeof GraciasInfinitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gracias-infinitas': typeof GraciasInfinitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gracias-infinitas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gracias-infinitas'
  id: '__root__' | '/' | '/gracias-infinitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraciasInfinitasRoute: typeof GraciasInfinitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gracias-infinitas': {
      id: '/gracias-infinitas'
      path: '/gracias-infinitas'
      fullPath: '/gracias-infinitas'
      preLoaderRoute: typeof GraciasInfinitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraciasInfinitasRoute: GraciasInfinitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
