/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromocionDeNegociosRouteImport } from './routes/promocion-de-negocios'
import { Route as OptimizacionDeNegociosRouteImport } from './routes/optimizacion-de-negocios'
import { Route as GraciasInfinitasRouteImport } from './routes/gracias-infinitas'
import { Route as DigitalizacionDeNegociosRouteImport } from './routes/digitalizacion-de-negocios'
import { Route as IndexRouteImport } from './routes/index'

const PromocionDeNegociosRoute = PromocionDeNegociosRouteImport.update({
  id: '/promocion-de-negocios',
  path: '/promocion-de-negocios',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizacionDeNegociosRoute = OptimizacionDeNegociosRouteImport.update({
  id: '/optimizacion-de-negocios',
  path: '/optimizacion-de-negocios',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasInfinitasRoute = GraciasInfinitasRouteImport.update({
  id: '/gracias-infinitas',
  path: '/gracias-infinitas',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalizacionDeNegociosRoute =
  DigitalizacionDeNegociosRouteImport.update({
    id: '/digitalizacion-de-negocios',
    path: '/digitalizacion-de-negocios',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digitalizacion-de-negocios': typeof DigitalizacionDeNegociosRoute
  '/gracias-infinitas': typeof GraciasInfinitasRoute
  '/optimizacion-de-negocios': typeof OptimizacionDeNegociosRoute
  '/promocion-de-negocios': typeof PromocionDeNegociosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digitalizacion-de-negocios': typeof DigitalizacionDeNegociosRoute
  '/gracias-infinitas': typeof GraciasInfinitasRoute
  '/optimizacion-de-negocios': typeof OptimizacionDeNegociosRoute
  '/promocion-de-negocios': typeof PromocionDeNegociosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digitalizacion-de-negocios': typeof DigitalizacionDeNegociosRoute
  '/gracias-infinitas': typeof GraciasInfinitasRoute
  '/optimizacion-de-negocios': typeof OptimizacionDeNegociosRoute
  '/promocion-de-negocios': typeof PromocionDeNegociosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/digitalizacion-de-negocios'
    | '/gracias-infinitas'
    | '/optimizacion-de-negocios'
    | '/promocion-de-negocios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/digitalizacion-de-negocios'
    | '/gracias-infinitas'
    | '/optimizacion-de-negocios'
    | '/promocion-de-negocios'
  id:
    | '__root__'
    | '/'
    | '/digitalizacion-de-negocios'
    | '/gracias-infinitas'
    | '/optimizacion-de-negocios'
    | '/promocion-de-negocios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalizacionDeNegociosRoute: typeof DigitalizacionDeNegociosRoute
  GraciasInfinitasRoute: typeof GraciasInfinitasRoute
  OptimizacionDeNegociosRoute: typeof OptimizacionDeNegociosRoute
  PromocionDeNegociosRoute: typeof PromocionDeNegociosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promocion-de-negocios': {
      id: '/promocion-de-negocios'
      path: '/promocion-de-negocios'
      fullPath: '/promocion-de-negocios'
      preLoaderRoute: typeof PromocionDeNegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizacion-de-negocios': {
      id: '/optimizacion-de-negocios'
      path: '/optimizacion-de-negocios'
      fullPath: '/optimizacion-de-negocios'
      preLoaderRoute: typeof OptimizacionDeNegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias-infinitas': {
      id: '/gracias-infinitas'
      path: '/gracias-infinitas'
      fullPath: '/gracias-infinitas'
      preLoaderRoute: typeof GraciasInfinitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digitalizacion-de-negocios': {
      id: '/digitalizacion-de-negocios'
      path: '/digitalizacion-de-negocios'
      fullPath: '/digitalizacion-de-negocios'
      preLoaderRoute: typeof DigitalizacionDeNegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalizacionDeNegociosRoute: DigitalizacionDeNegociosRoute,
  GraciasInfinitasRoute: GraciasInfinitasRoute,
  OptimizacionDeNegociosRoute: OptimizacionDeNegociosRoute,
  PromocionDeNegociosRoute: PromocionDeNegociosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
